language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t kienpv/docker-multiple-sample -f ./client/Dockerfile.dev ./client
     
script:
        - docker run -e CI=true kienpv/docker-multiple-sample npm test

after_success:
        - docker build -t kienpv/multi-client ./client
        - docker build -t kienpv/multi-nginx ./nginx
        - docker build -t kienpv/multi-server ./server
        - docker build -t kienpv/multi-worker ./worker
        
        # Login to the docker cli
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password=stdin

        # Take those images and push them to the docker hub
        - docker push kienpv/multi-client
        - docker push kienpv/multi-nginx
        - docker push kienpv/multi-server
        - docker push kienpv/multi-worker
